import asyncio
from dataclasses import replace
from unittest.mock import AsyncMock, patch

import pytest
from httpx import ASGITransport, AsyncClient

import api.main as main
from api.rag.config import RagConfig
from api.rag.context import evidence_size, select_context
from api.rag.retrieval import parse_hit, retrieve, resolve, RetrievalUnavailable
from api.rag.sources import decode_chunk_id
from api.search import build_query


def hit(text="machine learning " * 40, start=0, end=120000, episode="ep1", score=5, index=0):
    return {"_id": "autogenerated", "_score": score, "highlight": {"clip_text": ["WRONG EXCERPT"]},
            "_source": {"podcast_id": "show1", "episode_id": episode, "clip_index": index,
                        "clip_start_ms": start, "clip_end_ms": end, "clip_text": text,
                        "speakers": [2, 1, 2]}}


def clients(hits):
    es, pool = AsyncMock(), AsyncMock()
    es.search.return_value = {"hits": {"hits": hits}}
    pool.fetchrow.return_value = {"show_name": "Real Show", "episode_name": "Real Episode",
                                 "audio_link": None}
    return es, pool


@pytest.mark.asyncio
async def test_bm25_full_text_and_metadata():
    doc = hit()
    es, pool = clients([doc])
    result = await retrieve("machine learning", es, pool, RagConfig())
    body = es.search.call_args.kwargs["body"]
    assert body["query"] == build_query("machine learning", 0, 30)["query"]
    assert "highlight" not in body and "clip_text" in body["_source"]
    assert body["size"] == 30
    assert es.search.call_args.kwargs["index"] == "podcast_clips"
    source = result[0]
    assert source.excerpt == doc["_source"]["clip_text"] and len(source.excerpt) > 300
    assert source.show_name == "Real Show" and source.episode_name == "Real Episode"
    assert source.metadata_available and source.speakers == [1, 2]
    assert source.clip_index == 0 and source.clip_end_ms == 120000
    pool.fetchrow.assert_awaited_once()


def test_chunk_id_stable_and_content_sensitive():
    doc = hit()
    original = parse_hit(doc)
    doc["_id"] = "different-id"
    doc["_source"]["clip_index"] = 99
    assert parse_hit(doc).chunk_id == original.chunk_id
    assert replace(original, text=original.text + " ").chunk_id != original.chunk_id
    assert replace(original, episode_id="other").chunk_id != original.chunk_id
    assert decode_chunk_id(original.chunk_id)[:4] == ["show1", "ep1", 0, 120000]


def test_deduplicate_and_deterministic_order():
    one = parse_hit(hit())
    duplicate = replace(one, clip_index=4)
    two = parse_hit(hit(episode="ep2"))
    forward = select_context([duplicate, two, one], 6, 16000)
    reverse = select_context([one, two, duplicate], 6, 16000)
    assert forward == reverse
    assert len(forward) == 2
    assert next(c for c in forward if c.episode_id == "ep1").clip_index == 0


def test_overlap_suppresses_adjacent_but_preserves_other_episode():
    one = parse_hit(hit(end=119800, score=10))
    adjacent = parse_hit(hit(start=60000, end=179800, score=9))
    far = parse_hit(hit(start=120000, end=239800, score=8))
    other_episode = parse_hit(hit(episode="ep2", score=7))
    assert select_context([adjacent, other_episode, far, one], 6, 16000) == [one, far, other_episode]


def test_source_limit():
    candidates = [parse_hit(hit(episode=f"ep{i}")) for i in range(10)]
    assert len(select_context(candidates, 3, 16000)) == 3


def test_utf8_budget_skips_oversized_without_truncation():
    large = parse_hit(hit(text="x" * 101, score=10))
    one = parse_hit(hit(text="汉" * 20, episode="ep2", score=9))
    two = parse_hit(hit(text="z" * 40, episode="ep3", score=8))
    extra = parse_hit(hit(text="a", episode="ep4", score=7))
    selected = select_context([large, one, two, extra], 6, 100)
    assert selected == [one, two]
    assert sum(evidence_size(c.text) for c in selected) == 100


@pytest.mark.asyncio
async def test_no_results_or_only_oversized():
    es, pool = clients([])
    assert await retrieve("question", es, pool, RagConfig()) == []
    es.search.return_value = {"hits": {"hits": [hit(text="a" * 101)]}}
    assert await retrieve("question", es, pool, RagConfig(context_max_bytes=100)) == []
    pool.fetchrow.assert_not_called()


@pytest.mark.parametrize("failure", [OSError("private endpoint"), asyncio.TimeoutError()])
@pytest.mark.asyncio
async def test_es_failure(failure):
    es, pool = clients([])
    es.search.side_effect = failure
    with pytest.raises(RetrievalUnavailable):
        await retrieve("question", es, pool, RagConfig())
    pool.fetchrow.assert_not_called()


@pytest.mark.parametrize("raw", [{"timed_out": True}, {"_shards": {"failed": 1}}])
@pytest.mark.asyncio
async def test_partial_es_failure(raw):
    es, pool = clients([])
    es.search.return_value = raw
    with pytest.raises(RetrievalUnavailable):
        await retrieve("question", es, pool, RagConfig())


@pytest.mark.parametrize("failure", [None, OSError("database unavailable")])
@pytest.mark.asyncio
async def test_metadata_fallback(failure):
    es, pool = clients([hit()])
    pool.fetchrow.return_value = None
    pool.fetchrow.side_effect = failure
    sources = await retrieve("question", es, pool, RagConfig())
    assert sources[0].show_name == "Unknown Show"
    assert sources[0].episode_name == "Unknown Episode"
    assert not sources[0].metadata_available
    assert sources[0].episode_id == "ep1" and sources[0].excerpt == hit()["_source"]["clip_text"]


@pytest.mark.asyncio
async def test_source_resolution_checks_exact_hash_and_fixed_index():
    doc = hit()
    es, pool = clients([doc])
    chunk_id = parse_hit(doc).chunk_id
    source = await resolve(chunk_id, es, pool, RagConfig())
    assert source.chunk_id == chunk_id and source.excerpt == doc["_source"]["clip_text"]
    assert es.search.call_args.kwargs["index"] == "podcast_clips"
    assert "filter" in es.search.call_args.kwargs["body"]["query"]["bool"]
    doc["_source"]["clip_text"] = "changed text"
    assert await resolve(chunk_id, es, pool, RagConfig()) is None


@pytest.mark.parametrize("unknown", ["unknown", "https://example.com", "v1.e30", "v1." + "x" * 2048])
@pytest.mark.asyncio
async def test_invalid_source_ids_do_not_query(unknown):
    es, pool = clients([])
    assert await resolve(unknown, es, pool, RagConfig()) is None
    es.search.assert_not_called()


@pytest.mark.asyncio
async def test_resolver_pages_and_cap():
    original = parse_hit(hit(text="original"))
    es, pool = clients([])
    wrong = hit(text="changed")
    es.search.side_effect = [{"hits": {"hits": [wrong] * 100}},
                             {"hits": {"hits": [hit(text="original")]}}]
    assert (await resolve(original.chunk_id, es, pool, RagConfig())).excerpt == "original"
    es.search.side_effect = None
    es.search.return_value = {"hits": {"hits": [wrong] * 100}}
    with pytest.raises(RetrievalUnavailable):
        await resolve(original.chunk_id, es, pool, RagConfig())


@pytest.fixture
def enabled_app(monkeypatch):
    monkeypatch.setenv("RAG_ENABLED", "true")
    for name in ("RAG_LLM_API_KEY", "RAG_LLM_PROVIDER", "RAG_LLM_MODEL", "RAG_SOURCE_INDEX",
                 "RAG_CANDIDATE_LIMIT", "RAG_MAX_SOURCES", "RAG_CONTEXT_MAX_BYTES"):
        monkeypatch.delenv(name, raising=False)
    es, pool = clients([hit()])
    cache = AsyncMock()
    monkeypatch.setattr(main, "_es_client", es)
    monkeypatch.setattr(main, "_db_pool", pool)
    monkeypatch.setattr(main, "_cache_client", cache)
    return main.create_app(), es, pool, cache


@pytest.mark.asyncio
async def test_enabled_ask_without_keys_and_source_route(enabled_app):
    app, es, pool, cache = enabled_app
    with patch("socket.socket.connect", side_effect=AssertionError("No external provider allowed")):
        async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as client:
            response = await client.post("/ask", json={"question": "machine learning"})
            assert response.status_code == 200
            body = response.json()
            assert body["status"] == "generation_unavailable" and body["answer"] is None
            assert body["reason"] == "llm_not_configured" and body["retrieval_mode"] == "bm25"
            source = body["sources"][0]
            resolved = await client.get("/sources/" + source["chunk_id"])
            assert resolved.status_code == 200 and resolved.json() == source
            es.search.return_value = {"hits": {"hits": []}}
            assert (await client.get("/sources/" + source["chunk_id"])).status_code == 404
            empty = await client.post("/ask", json={"question": "unknown"})
            assert empty.json()["status"] == "insufficient_context"
            es.search.side_effect = OSError("private connection detail")
            failure = await client.post("/ask", json={"question": "question"})
            assert failure.status_code == 503 and failure.json() == {"detail": "retrieval_unavailable"}
            assert (await client.get("/sources/" + source["chunk_id"])).status_code == 503
            assert (await client.get("/health")).json() == {"status": "ok"}
    assert not cache.mock_calls


@pytest.mark.asyncio
async def test_unsupported_provider_preserves_evidence(enabled_app, monkeypatch):
    _, es, pool, _ = enabled_app
    for name in ("RAG_LLM_API_KEY", "RAG_LLM_PROVIDER", "RAG_LLM_MODEL"):
        monkeypatch.setenv(name, "test-placeholder")
    app = main.create_app()
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as client:
        body = (await client.post("/ask", json={"question": "question"})).json()
    assert body["reason"] == "unsupported_provider" and body["answer"] is None
    assert body["sources"] and "test-placeholder" not in str(body)


@pytest.mark.asyncio
async def test_disabled_source_route_has_no_io(enabled_app, monkeypatch):
    _, es, _, _ = enabled_app
    monkeypatch.setenv("RAG_ENABLED", "false")
    async with AsyncClient(transport=ASGITransport(app=main.create_app()), base_url="http://test") as client:
        assert (await client.get("/sources/" + parse_hit(hit()).chunk_id)).status_code == 404
    es.search.assert_not_called()


def test_config_invalid_limits_fail_to_defaults(monkeypatch):
    for name, value in {"RAG_CANDIDATE_LIMIT": "bad", "RAG_MAX_SOURCES": "0",
                        "RAG_CONTEXT_MAX_BYTES": "999999", "RAG_SOURCE_INDEX": "*"}.items():
        monkeypatch.setenv(name, value)
    config = RagConfig.from_env()
    assert (config.candidate_limit, config.max_sources, config.context_max_bytes) == (30, 6, 16000)
    assert config.source_index == "podcast_clips"
