"""Versioned source IDs resolve without a registry or legacy document changes.

v1.<base64url(canonical JSON [show, episode, start, end, SHA256(exact text)])>
uses UTF-8, compact separators, and no padding. It is an identifier, not an
authorization token. Only matching evidence in the configured corpus is served.
Clip index, speakers, and Elasticsearch autogenerated IDs do not define identity.
"""

import base64
import binascii
import hashlib
import json
import re
from dataclasses import dataclass


@dataclass(frozen=True)
class Evidence:
    podcast_id: str
    episode_id: str
    start_ms: int
    end_ms: int
    text: str
    clip_index: int
    speakers: tuple[int, ...]
    score: float = 0.0

    @property
    def chunk_id(self) -> str:
        payload = [self.podcast_id, self.episode_id, self.start_ms, self.end_ms,
                   hashlib.sha256(self.text.encode("utf-8")).hexdigest()]
        raw = json.dumps(payload, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
        return "v1." + base64.urlsafe_b64encode(raw).decode("ascii").rstrip("=")


def decode_chunk_id(chunk_id: str) -> list | None:
    if len(chunk_id) > 2048 or not re.fullmatch(r"v1\.[A-Za-z0-9_-]+", chunk_id):
        return None
    try:
        encoded = chunk_id[3:]
        raw = base64.urlsafe_b64decode(encoded + "=" * (-len(encoded) % 4))
        value = json.loads(raw)
        if not isinstance(value, list) or len(value) != 5:
            return None
        show, episode, start, end, digest = value
        if not all(isinstance(x, str) and x for x in (show, episode, digest)):
            return None
        if type(start) is not int or type(end) is not int or not 0 <= start < end:
            return None
        if not re.fullmatch(r"[0-9a-f]{64}", digest):
            return None
        canonical = json.dumps(value, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
        if raw != canonical:
            return None
        return value
    except (ValueError, UnicodeError, binascii.Error):
        return None
